### PR TITLE
Version 1.2.2 → 1.3.0

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Would it be possible to get a new release please. Thanks in advance!

### CODE REVIEW

**Review by ixmatus — APPROVED** [review]
Thanks for the CHANGELOG entry and version bump. I believe I have release permissions so I can go ahead and do that.

**Comment by ixmatus** [comment]
Here is the package candidate: https://hackage.haskell.org/package/proto3-wire-1.3.0/candidate.

CC: @Gabriella439 I can't remember if Hackage automatically generates documentation these days or if I need to build and upload documentation separately?

**Comment by TristanCacqueray** [comment]
@ixmatus Thank you very much!

**Comment by gbaz** [comment]
hackage doesn't generate candidate documentation though, just genuine documentation, and also "the buildbox doesn't have proto3 installed" will likely be a reason most proto3 things will need their own docs built.

**Comment by ixmatus** [comment]
Okay, I went ahead and published the package candidate.

**Pull request merged**
